// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";  // <-- Add this import

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trackly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased min-h-screen")}>
        {/* Wrap your entire app with NuqsAdapter */}
        <NuqsAdapter>
          {children}
        </NuqsAdapter>
      </body>
    </html>
  );
}
